    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/checkout@v2
            with:
              repository: jblang04/Java-Maven-Actions-Tests #Repositorio publico con los test
              #token: ${{ secrets.GH_PAT }} #Solo si es privado el repositorio
              path: ./spec #Carpeta del repositorio donde se descargaran los test
          - uses: education/autograding@v1
